### ISSUE TITLE
10022erroor

### ISSUE THREAD

**Issue by legend0000** [dsiroky/snakemq#15]
i use snakemq in server client . But there has a error(10022),please help me!!!

**Comment by dsiroky** [comment]
Hi! This is a very non-detailed report :-) Can you provide a minimal example? When does it happen? Any traceback?

**Comment by legend0000** [comment]
Traceback (most recent call last):
  File "D:\programs\Python27\ArcGISx6410.3\lib\threading.py", line 810, in __boo
tstrap_inner
    self.run()
  File "D:\programs\Python27\ArcGISx6410.3\lib\site-packages\watchdog\observers\
api.py", line 199, in run
    self.dispatch_events(self.event_queue, self.timeout)
  File "D:\programs\Python27\ArcGISx6410.3\lib\site-packages\watchdog\observers\
api.py", line 368, in dispatch_events
    handler.dispatch(event)
  File "D:\programs\Python27\ArcGISx6410.3\lib\site-packages\watchdog\events.py"
, line 330, in dispatch
    _method_map[event_type](event)
  File ".\server.py", line 263, in on_created
  File ".\server.py", line 390, in TaskWatcher
  File "D:\programs\Python27\ArcGISx6410.3\lib\site-packages\snakemq\link.py", l
ine 277, in cleanup
    self.handle_close(sock)
  File "D:\programs\Python27\ArcGISx6410.3\lib\site-packages\snakemq\link.py", l
ine 655, in handle_close
    sock.close()
  File "D:\programs\Python27\ArcGISx6410.3\lib\site-packages\snakemq\link.py", l
ine 165, in close
    self.sock.shutdown(socket.SHUT_RDWR)
  File "D:\programs\Python27\ArcGISx6410.3\lib\socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 10022]

**Comment by dsiroky** [comment]
This looks like the _sock was not properly initialized or was already closed. I can't help you with only a traceback. I need some minimal example how to reproduce it.
