### ISSUE TITLE
RPC Signal fails with KeyError looking for "req_id"

### ISSUE THREAD

**Issue by jonEbird** [dsiroky/snakemq#16]
I'd like to use the RPC mechanism and I'm also exploring the signal support but it looks like there is a bug somewhere that is failing to set "req_id". If I follow the example code, I get the following stack trace:
```raw
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_i
nner                                                                                                                                      
    self.run()
  File "/opt/homebrew/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Users/jonmiller/venv/snakemq/lib/python2.7/site-packages/snakemq/rpc.py", line 149, in call_method
    b2a_hex(params["req_id"])))
KeyError: 'req_id'
```
I'm using the latest 1.4 version.

**Comment by dsiroky** [comment]
Could you please provide a minimal code that reproduces this error?

**Comment by jonEbird** [comment]
Here is a sample program that you can call separately in two terminals and _hopefully_ see the same error:
```raw
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_i
nner                                                                                                                                      
    self.run()
  File "/opt/homebrew/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Users/jonmiller/venv/snakemq/lib/python2.7/site-packages/snakemq/rpc.py", line 149, in call_method
    b2a_hex(params["req_id"])))
KeyError: 'req_id'
```

Here is the code I used to try it out:
```python
#!/usr/bin/env python

import sys
import logging
import threading
import time

import snakemq.link
import snakemq.messaging
import snakemq.packeter
import snakemq.rpc

AGENT_IDENT = "agent"
EXECUTOR_IDENT = "executor"


def agent(name="Jon"):
    IDENT = AGENT_IDENT
    REMOTE_IDENTITY = EXECUTOR_IDENT

    link = snakemq.link.Link()
    link.add_listener(("", 4000))

    tr = snakemq.packeter.Packeter(link)
    messaging = snakemq.messaging.Messaging(IDENT, "", tr, None)
    rh = snakemq.messaging.ReceiveHook(messaging)
    crpc = snakemq.rpc.RpcClient(rh)

    proxy = crpc.get_proxy(REMOTE_IDENTITY, REMOTE_IDENTITY)

    proxy.signal_end.as_signal(10)

    t = threading.Thread(target=link.loop)
    t.setDaemon(1)
    t.start()

    # Ensure connection
    while not messaging._conn_by_ident.keys():
        time.sleep(1)

    try:
        # Simple RPC call
        proxy.say_hi(name)

        # try a signal call
        proxy.signal_end()
    except Exception as exc:
        print("remote traceback", str(exc.__remote_traceback__))
    finally:
        link.stop()

    print("%s is done. Quitting." % IDENT)
    t.join()


class RPCHelper(object):
    def say_hi(self, name="George"):
        print("Well hello, %s." % name)

    @snakemq.rpc.as_signal
    def signal_end(self):
        print("This is the end, sweet world.")


def executor():
    IDENT = "executor"

    link = snakemq.link.Link()
    link.add_connector(("localhost", 4000))

    tr = snakemq.packeter.Packeter(link)
    messaging = snakemq.messaging.Messaging(IDENT, "", tr)
    rh = snakemq.messaging.ReceiveHook(messaging)
    srpc = snakemq.rpc.RpcServer(rh)

    srpc.register_object(RPCHelper(), IDENT)

    t = threading.Thread(target=link.loop)
    t.setDaemon(1)
    t.start()

    # Wait for connection
    while not messaging._conn_by_ident.keys():
        time.sleep(0.25)

    print("Connected.")

    # Wait for disconnect
    while messaging._conn_by_ident.keys():
        time.sleep(1)

    print("Agent has disconnected. We will stop now too.")

    # Shutdown
    link.stop()
    t.join()


def main():
    try:
        action = sys.argv[1]
    except IndexError:
        print("usage: %s agent|executor" % sys.argv[0])
        exit(1)

    snakemq.init_logging()
    logger = logging.getLogger("snakemq")
    logger.setLevel(logging.INFO)

    if action == 'agent':
        if len(sys.argv) > 2:
            name = sys.argv[2]
        else:
            name = 'Peter'

        agent(name)

    elif action == 'executor':
        executor()

    else:
        print("ERROR: unknown command %s" % action)
        exit(1)


if __name__ == '__main__':
    main()
```

If I stick to just plain RPC calls there is no problem. Thanks.

**Comment by dsiroky** [comment]
Try this commit: https://github.com/dsiroky/snakemq/commit/67e4b93336c5a791c2299b2748d3de83c5eb328f

**Comment by jonEbird** [comment]
Yep! That has fixed the issue. Had I known it was only affecting the debug code I would have submitted a PR myself. Can I expect this to make its way into a 1.5 in the future? Thanks.

**Comment by dsiroky** [comment]
1.5 released. Thank you for the report.
